#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

ini_set('display_errors', 1);
error_reporting(E_ALL);

/* Register Dotenv */
(new \Dotenv\Dotenv(__DIR__ . '/../..'))->load();

/* Load Configuration */
\App\Helpers\Config::bootstrap(__DIR__ . '/../../config');

/* Boot Eloquent ORM */
require __DIR__ . '/db.php';

$redis = new \Redis;
$redis->connect('localhost');
$redis->setOption(Redis::OPT_PREFIX, config['queue.name'] . ':');

$driver = new \Bernard\Driver\PhpRedisDriver($redis);

$factory = new \Bernard\QueueFactory\PersistentFactory(
    $driver,
    new \Bernard\Serializer\SimpleSerializer()
);

$middleware = new \Bernard\Middleware\MiddlewareBuilder;
$middleware->push(new \Bernard\Middleware\ErrorLogFactory);

$router = new \Bernard\Router\SimpleRouter($config['queue.map']);

$consumer = new \Bernard\Consumer($router, $middleware);

$consumer->consume($factory->create('default'));

exit();