<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace App\DataSource\User;

use Atlas\Table\Row;

/**
 * @property mixed $id int(10,0) unsigned NOT NULL
 * @property mixed $name varchar(255) NOT NULL
 * @property mixed $email varchar(255) NOT NULL
 * @property mixed $password varchar(255) NOT NULL
 * @property mixed $created_at datetime NOT NULL
 * @property mixed $remember_token varchar(60) NOT NULL
 */
class UserRow extends Row
{
    protected $cols = [
        'id' => null,
        'name' => null,
        'email' => null,
        'password' => null,
        'created_at' => 'current_timestamp()',
        'remember_token' => '\'\'',
    ];
}
