<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace App\DataSource\User;

use Atlas\Table\Table;

/**
 * @method UserRow|null fetchRow($primaryVal)
 * @method UserRow[] fetchRows(array $primaryVals)
 * @method UserTableSelect select(array $whereEquals = [])
 * @method UserRow newRow(array $cols = [])
 * @method UserRow newSelectedRow(array $cols)
 */
class UserTable extends Table
{
    const DRIVER = 'mysql';

    const NAME = 'User';

    const COLUMNS = [
        'id' => array(
            'name' => 'id',
            'type' => 'int unsigned',
            'size' => 10,
            'scale' => 0,
            'notnull' => true,
            'default' => null,
            'autoinc' => true,
            'primary' => true,
            'options' => null,
        ),
        'name' => array(
            'name' => 'name',
            'type' => 'varchar',
            'size' => 255,
            'scale' => null,
            'notnull' => true,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ),
        'email' => array(
            'name' => 'email',
            'type' => 'varchar',
            'size' => 255,
            'scale' => null,
            'notnull' => true,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ),
        'password' => array(
            'name' => 'password',
            'type' => 'varchar',
            'size' => 255,
            'scale' => null,
            'notnull' => true,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ),
        'created_at' => array(
            'name' => 'created_at',
            'type' => 'datetime',
            'size' => null,
            'scale' => null,
            'notnull' => true,
            'default' => 'current_timestamp()',
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ),
        'remember_token' => array(
            'name' => 'remember_token',
            'type' => 'varchar',
            'size' => 60,
            'scale' => null,
            'notnull' => true,
            'default' => '\'\'',
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ),
    ];

    const COLUMN_NAMES = [
        'id',
        'name',
        'email',
        'password',
        'created_at',
        'remember_token',
    ];

    const COLUMN_DEFAULTS = [
        'id' => null,
        'name' => null,
        'email' => null,
        'password' => null,
        'created_at' => 'current_timestamp()',
        'remember_token' => '\'\'',
    ];

    const PRIMARY_KEY = [
        'id',
    ];

    const AUTOINC_COLUMN = 'id';

    const AUTOINC_SEQUENCE = null;
}
