<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace App\DataSource\User;

/**
 * @property mixed $id int(10,0) unsigned NOT NULL
 * @property mixed $name varchar(255) NOT NULL
 * @property mixed $email varchar(255) NOT NULL
 * @property mixed $password varchar(255) NOT NULL
 * @property mixed $created_at datetime NOT NULL
 * @property mixed $remember_token varchar(60) NOT NULL
 */
trait UserFields
{
}
