<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace App\DataSource\Article;

use Atlas\Table\Table;

/**
 * @method ArticleRow|null fetchRow($primaryVal)
 * @method ArticleRow[] fetchRows(array $primaryVals)
 * @method ArticleTableSelect select(array $whereEquals = [])
 * @method ArticleRow newRow(array $cols = [])
 * @method ArticleRow newSelectedRow(array $cols)
 */
class ArticleTable extends Table
{
    const DRIVER = 'mysql';

    const NAME = 'Article';

    const COLUMNS = [
        'id' => [
            'name' => 'id',
            'type' => 'int unsigned',
            'size' => 10,
            'scale' => 0,
            'notnull' => true,
            'default' => null,
            'autoinc' => true,
            'primary' => true,
            'options' => null,
        ],
        'slug' => array(
            'name' => 'slug',
            'type' => 'varchar',
            'size' => 255,
            'scale' => null,
            'notnull' => true,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ),
        'title' => array(
            'name' => 'title',
            'type' => 'varchar',
            'size' => 255,
            'scale' => null,
            'notnull' => true,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ),
        'content' => array(
            'name' => 'content',
            'type' => 'text',
            'size' => 65535,
            'scale' => null,
            'notnull' => true,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ),
        'is_published' => array(
            'name' => 'is_published',
            'type' => 'int unsigned',
            'size' => 10,
            'scale' => 0,
            'notnull' => true,
            'default' => '0',
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ),
        'social_image' => array(
            'name' => 'social_image',
            'type' => 'varchar',
            'size' => 255,
            'scale' => null,
            'notnull' => false,
            'default' => 'NULL',
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ),
        'seo_title' => array(
            'name' => 'seo_title',
            'type' => 'varchar',
            'size' => 255,
            'scale' => null,
            'notnull' => false,
            'default' => 'NULL',
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ),
        'seo_description' => array(
            'name' => 'seo_description',
            'type' => 'varchar',
            'size' => 255,
            'scale' => null,
            'notnull' => false,
            'default' => 'NULL',
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ),
        'seo_keywords' => array(
            'name' => 'seo_keywords',
            'type' => 'varchar',
            'size' => 255,
            'scale' => null,
            'notnull' => false,
            'default' => 'NULL',
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ),
        'created_at' => array(
            'name' => 'created_at',
            'type' => 'datetime',
            'size' => null,
            'scale' => null,
            'notnull' => true,
            'default' => 'current_timestamp()',
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ),
        'updated_at' => array(
            'name' => 'updated_at',
            'type' => 'datetime',
            'size' => null,
            'scale' => null,
            'notnull' => false,
            'default' => 'NULL',
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ),
    ];

    const COLUMN_NAMES = [
        'id',
        'slug',
        'title',
        'content',
        'is_published',
        'social_image',
        'seo_title',
        'seo_description',
        'seo_keywords',
        'created_at',
        'updated_at',
    ];

    const COLUMN_DEFAULTS = [
        'id' => null,
        'slug' => null,
        'title' => null,
        'content' => null,
        'is_published' => '0',
        'social_image' => 'NULL',
        'seo_title' => 'NULL',
        'seo_description' => 'NULL',
        'seo_keywords' => 'NULL',
        'created_at' => 'current_timestamp()',
        'updated_at' => 'NULL',
    ];

    const PRIMARY_KEY = [
        'id',
    ];

    const AUTOINC_COLUMN = 'id';

    const AUTOINC_SEQUENCE = null;
}
