<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace App\DataSource\Tag;

/**
 * @property mixed $id int(10,0) unsigned NOT NULL
 * @property mixed $slug varchar(255) NOT NULL
 * @property mixed $title varchar(255) NOT NULL
 * @property mixed $content text(65535) NOT NULL
 * @property mixed $seo_title varchar(255)
 * @property mixed $seo_description varchar(255)
 * @property mixed $seo_keywords varchar(255)
 * @property mixed $created_at datetime NOT NULL
 * @property mixed $updated_at datetime
 */
trait TagFields
{
}
