<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace App\DataSource\ArticleTag;

use Atlas\Table\Row;

/**
 * @property mixed $id int(10,0) unsigned NOT NULL
 * @property mixed $id__Article int(10,0) unsigned NOT NULL
 * @property mixed $id__Tag int(10,0) unsigned NOT NULL
 */
class ArticleTagRow extends Row
{
    protected $cols = [
        'id' => null,
        'id__Article' => null,
        'id__Tag' => null,
    ];
}
