<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace App\DataSource\ArticleTag;

/**
 * @property mixed $id int(10,0) unsigned NOT NULL
 * @property mixed $id__Article int(10,0) unsigned NOT NULL
 * @property mixed $id__Tag int(10,0) unsigned NOT NULL
 */
trait ArticleTagFields
{
}
