<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace App\DataSource\ArticleTag;

use Atlas\Table\Table;

/**
 * @method ArticleTagRow|null fetchRow($primaryVal)
 * @method ArticleTagRow[] fetchRows(array $primaryVals)
 * @method ArticleTagTableSelect select(array $whereEquals = [])
 * @method ArticleTagRow newRow(array $cols = [])
 * @method ArticleTagRow newSelectedRow(array $cols)
 */
class ArticleTagTable extends Table
{
    const DRIVER = 'mysql';

    const NAME = 'Article_Tag';

    const COLUMNS = [
        'id' => [
            'name' => 'id',
            'type' => 'int unsigned',
            'size' => 10,
            'scale' => 0,
            'notnull' => true,
            'default' => null,
            'autoinc' => true,
            'primary' => true,
            'options' => null,
        ],
        'id__Article' => [
            'name' => 'id__Article',
            'type' => 'int unsigned',
            'size' => 10,
            'scale' => 0,
            'notnull' => true,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
        'id__Tag' => [
            'name' => 'id__Tag',
            'type' => 'int unsigned',
            'size' => 10,
            'scale' => 0,
            'notnull' => true,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
    ];

    const COLUMN_NAMES = [
        'id',
        'id__Article',
        'id__Tag',
    ];

    const COLUMN_DEFAULTS = [
        'id' => null,
        'id__Article' => null,
        'id__Tag' => null,
    ];

    const PRIMARY_KEY = [
        'id',
    ];

    const AUTOINC_COLUMN = 'id';

    const AUTOINC_SEQUENCE = null;
}
